services:
  - type: web
    name: ch-auto-subtitle
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 1100
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: ADMIN_PASSCODE
        value: CHHIT
